//This file was generated by script swreg2regmap.py

//register address mapping
#define KNN_RESET 0
#define KNN_ENABLE 1
#define KNN_START 2
#define DATAP_REG 3
#define LABEL_REG 4
#define OUT_REG 5
#define BANK_LABELS0 6
#define BANK_LABELS1 7
#define BANK_LABELS2 8
#define BANK_LABELS3 9
#define BANK_TESTP0 10
#define BANK_TESTP1 11
#define BANK_TESTP2 12
#define BANK_TESTP3 13
